### PR TITLE
More Catching up to Schema 

### PR DESCRIPTION
**Pull request by dan-fritchman**
Notes where our schema change has clearly broken netlisting, and we haven't noticed it yet. 

@growly PLEASE DONT MERGE ME YET 
I'm not ready yet, see it says "DRAFT" right there.

### CODE REVIEW

**Comment by growly** [comment]
can I merge this yet?

**Comment by dan-fritchman** [comment]
I suppose you can if you really want. 
But the changes are solely comments which say:

## FIXME! this is NOT the updated schema

Personally find it more valuable to leave this PR until actually fixing them instead. Or if we have other reasons to wanna get this closed, maybe we can make it an issue or somesuch.

**Comment by growly** [comment]
oh nah i was taking the piss

**Comment by dan-fritchman** [comment]
Merged the ngspice content from #18 into here. 

@aviralpandey @cem-yalcin - this should enable your ongoing work.

**Pull request merged**
